"""update bookings

Revision ID: 8ab106975e7b
Revises: ddf3a1c0632f
Create Date: 2025-05-26 22:57:22.696566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ab106975e7b'
down_revision: Union[str, None] = 'ddf3a1c0632f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('total_days', sa.INTEGER(), sa.Computed('(date_to - date_from)', ), nullable=True))
    op.drop_column('bookings', 'total_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('total_price', sa.INTEGER(), sa.Computed('(date_to - date_from)', persisted=True), autoincrement=False, nullable=True))
    op.drop_column('bookings', 'total_days')
    # ### end Alembic commands ###
