"""create hotels , rooms table add s to sevises

Revision ID: ddf3a1c0632f
Revises: 4bbeb39bdafb
Create Date: 2025-05-26 21:05:31.291105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddf3a1c0632f'
down_revision: Union[str, None] = '4bbeb39bdafb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('services', sa.JSON(), nullable=True))
    op.drop_column('hotels', 'service')
    op.add_column('rooms', sa.Column('services', sa.JSON(), nullable=False))
    op.drop_column('rooms', 'service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('service', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('rooms', 'services')
    op.add_column('hotels', sa.Column('service', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('hotels', 'services')
    # ### end Alembic commands ###
